-- return {
--   { "ellisonleao/gruvbox.nvim", enabled = true },
--   { "nvim-tree/nvim-web-devicons", enabled = true },
--   { "MunifTanjim/nui.nvim", enabled = true },
--   { "s1n7ax/nvim-window-picker", enabled = true },
--   { "nvim-lua/plenary.nvim", enabled = true },

--   { "chrisgrieser/nvim-spider", enabled = false },
--   { "NGPONG/matchparen.nvim", enabled = true },
--   { "NGPONG/multicursors.nvim", enabled = true },
--   -- { "NGPONG/hydra.nvim" },
--   { "smoka7/hop.nvim", enabled = true },
--   { "stevearc/conform.nvim", enabled = true },
--   { "numToStr/Comment.nvim", enabled = true },
--   { "NGPONG/autoclose.nvim", enabled = true },
--   { "svban/YankAssassin.nvim", enabled = true }

--   { "folke/todo-comments.nvim", enabled = true },
--   { "folke/trouble.nvim", enabled = true },
--   -- { "b0o/nvim-tree-preview.lua" },
--   { "nvim-tree/nvim-tree.lua", enabled = true },
--   { "rcarriga/nvim-notify", enabled = true },
--   { "echasnovski/mini.cursorword", enabled = true },
--   { "echasnovski/mini.indentscope", enabled = true },
--   { "nvim-lualine/lualine.nvim", enabled = true },
--   { "NGPONG/marks.nvim", enabled = true },
--   { "lewis6991/gitsigns.nvim", enabled = true },
--   { "stevearc/dressing.nvim", enabled = true },
--   -- { "j-hui/fidget.nvim" },
--   { "NGPONG/barbecue.nvim", enabled = true },
--   -- { "SmiteshP/nvim-navic" },
--   { "akinsho/bufferline.nvim", enabled = true },

--   { "hrsh7th/nvim-cmp", enabled = true },
--   -- { "FelipeLema/cmp-async-path" },
--   -- { "hrsh7th/cmp-buffer" },
--   -- { "hrsh7th/cmp-cmdline" },
--   -- { "hrsh7th/cmp-nvim-lsp" },
--   -- { "hrsh7th/cmp-nvim-lsp-signature-help" },
--   -- { "lukas-reineke/cmp-under-comparator" },
--   -- { "saadparwaiz1/cmp_luasnip" },
--   -- { "L3MON4D3/LuaSnip" },

--   { "nvim-treesitter/nvim-treesitter", enabled = true },
--   -- { "nvim-treesitter/nvim-treesitter-textobjects" },

--   -- { "NGPONG/lsp_signature.nvim" },
--   -- { "williamboman/mason-lspconfig.nvim" },
--   -- { "WhoIsSethDaniel/mason-tool-installer.nvim" },
--   { "williamboman/mason.nvim", enabed = true },
--   -- { "p00f/clangd_extensions.nvim" },
--   { "neovim/nvim-lspconfig", enabled = true },

--   { "nvim-telescope/telescope.nvim", enabled = true },
--   -- { "nvim-telescope/telescope-fzf-native.nvim" },
--   -- { "NGPONG/telescope-live-grep-args.nvim" },
--   -- { "nvim-telescope/telescope-smart-history.nvim" },
--   { "nvim-neo-tree/neo-tree.nvim", enabled = false },
--   { "stevearc/profile.nvim", enabled = false },
--   { "NGPONG/which-key.nvim", enabled = false },
-- }

return {
  { "ellisonleao/gruvbox.nvim", enabled = true },
  { "nvim-tree/nvim-web-devicons", enabled = true },
  { "MunifTanjim/nui.nvim", enabled = true },
  { "s1n7ax/nvim-window-picker", enabled = true },
  { "nvim-lua/plenary.nvim", enabled = true },
  { "smoka7/hop.nvim", enabled = true },
  { "svban/YankAssassin.nvim", enabled = true },
  { "rcarriga/nvim-notify", enabled = false },
  { "nvim-treesitter/nvim-treesitter", enabled = true },
  -- { "nvim-treesitter/nvim-treesitter-textobjects" },
  { "NGPONG/vim-tranquille", enabled = true },

  { "chrisgrieser/nvim-spider", enabled = false },
  { "NGPONG/matchparen.nvim", enabled = false },
  { "NGPONG/multicursors.nvim", enabled = false },
  -- { "NGPONG/hydra.nvim" },
  { "stevearc/conform.nvim", enabled = false },
  { "numToStr/Comment.nvim", enabled = false },
  { "NGPONG/autoclose.nvim", enabled = false },

  { "folke/todo-comments.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
  { "NGPONG/which-key.nvim", enabled = false },
  -- { "b0o/nvim-tree-preview.lua" },
  { "nvim-tree/nvim-tree.lua", enabled = false },
  { "echasnovski/mini.cursorword", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "nvim-lualine/lualine.nvim", enabled = false },
  { "NGPONG/marks.nvim", enabled = false },
  { "lewis6991/gitsigns.nvim", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  -- { "j-hui/fidget.nvim" },
  { "NGPONG/barbecue.nvim", enabled = false },
  -- { "SmiteshP/nvim-navic" },
  { "akinsho/bufferline.nvim", enabled = false },

  { "hrsh7th/nvim-cmp", enabled = false },
  -- { "FelipeLema/cmp-async-path" },
  -- { "hrsh7th/cmp-buffer" },
  -- { "hrsh7th/cmp-cmdline" },
  -- { "hrsh7th/cmp-nvim-lsp" },
  -- { "hrsh7th/cmp-nvim-lsp-signature-help" },
  -- { "lukas-reineke/cmp-under-comparator" },
  -- { "saadparwaiz1/cmp_luasnip" },
  -- { "L3MON4D3/LuaSnip" },

  -- { "NGPONG/lsp_signature.nvim" },
  -- { "williamboman/mason-lspconfig.nvim", enabed = false },
  -- { "WhoIsSethDaniel/mason-tool-installer.nvim", enabed = false },
  { "williamboman/mason.nvim", enabled = false },
  -- { "p00f/clangd_extensions.nvim" },
  { "neovim/nvim-lspconfig", enabled = false },

  { "nvim-telescope/telescope.nvim", enabled = false },
  -- { "nvim-telescope/telescope-fzf-native.nvim" },
  -- { "NGPONG/telescope-live-grep-args.nvim" },
  -- { "nvim-telescope/telescope-smart-history.nvim" },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "stevearc/profile.nvim", enabled = false }
}