local M = {}

M.setup = function()
  vim.api.nvim_set_hl(0, "TroubleNormal", { bg = vim.__color.dark0_soft })
  vim.api.nvim_set_hl(0, "TroublePreview", { link = "Search" })
  vim.api.nvim_set_hl(0, "TroubleIndent", { fg = vim.__color.dark4 })
  vim.api.nvim_set_hl(0, "TroubleFoldIcon", { fg = vim.__color.dark4 })
  vim.api.nvim_set_hl(0, "TroubleSignOther", { fg = vim.__color.bright_green })
  vim.api.nvim_set_hl(0, "TroubleSignHint", { link = "DiagnosticHint" })
  vim.api.nvim_set_hl(0, "TroubleSignError", { link = "DiagnosticError" })
  vim.api.nvim_set_hl(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
  vim.api.nvim_set_hl(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
  vim.api.nvim_set_hl(0, "TroubleCount", { fg = vim.__color.bright_orange, bg = vim.__color.dark2 })
  vim.api.nvim_set_hl(0, "TroubleIconDirectory", { fg = vim.__color.bright_yellow })
  vim.api.nvim_set_hl(0, "TroubleIndentFoldClosed", { link = "TroubleIndent" })
  vim.api.nvim_set_hl(0, "TroubleTextHint", { fg = vim.__color.light1 })
  vim.api.nvim_set_hl(0, "TroubleTextInformation", { fg = vim.__color.light1 })
  vim.api.nvim_set_hl(0, "TroubleTextWarning", { fg = vim.__color.light1 })
  vim.api.nvim_set_hl(0, "TroubleTextError", { fg = vim.__color.light1 })
  vim.api.nvim_set_hl(0, "TroubleFilename", { fg = vim.__color.light1 })
  vim.api.nvim_set_hl(0, "TroublePos", { fg = vim.__color.dark3 })
  vim.api.nvim_set_hl(0, "TroubleDirectory", { fg = vim.__color.light1 })
  vim.api.nvim_set_hl(0, "TroubleInvalidPos", { fg = vim.__color.light1, bg = vim.__color.bright_red })

  vim.api.nvim_set_hl(0, "TroubleIconDirectory", { fg = vim.__color.bright_yellow })
  vim.api.nvim_set_hl(0, "TroubleIconArray", { link = vim.__icons.lsp_kinds.Array.hl })
  vim.api.nvim_set_hl(0, "TroubleIconBoolean", { link = vim.__icons.lsp_kinds.Boolean.hl })
  vim.api.nvim_set_hl(0, "TroubleIconClass", { link = vim.__icons.lsp_kinds.Class.hl })
  vim.api.nvim_set_hl(0, "TroubleIconConstant", { link = vim.__icons.lsp_kinds.Constant.hl })
  vim.api.nvim_set_hl(0, "TroubleIconConstructor", { link = vim.__icons.lsp_kinds.Constructor.hl })
  vim.api.nvim_set_hl(0, "TroubleIconEnum", { link = vim.__icons.lsp_kinds.Enum.hl })
  vim.api.nvim_set_hl(0, "TroubleIconEnumMember", { link = vim.__icons.lsp_kinds.EnumMember.hl })
  vim.api.nvim_set_hl(0, "TroubleIconEvent", { link = vim.__icons.lsp_kinds.Event.hl })
  vim.api.nvim_set_hl(0, "TroubleIconField", { link = vim.__icons.lsp_kinds.Field.hl })
  vim.api.nvim_set_hl(0, "TroubleIconFile", { link = vim.__icons.lsp_kinds.File.hl })
  vim.api.nvim_set_hl(0, "TroubleIconFunction", { link = vim.__icons.lsp_kinds.Function.hl })
  vim.api.nvim_set_hl(0, "TroubleIconInterface", { link = vim.__icons.lsp_kinds.Interface.hl })
  vim.api.nvim_set_hl(0, "TroubleIconKey", { link = vim.__icons.lsp_kinds.Key.hl })
  vim.api.nvim_set_hl(0, "TroubleIconMethod", { link = vim.__icons.lsp_kinds.Method.hl })
  vim.api.nvim_set_hl(0, "TroubleIconModule", { link = vim.__icons.lsp_kinds.Module.hl })
  vim.api.nvim_set_hl(0, "TroubleIconNamespace", { link = vim.__icons.lsp_kinds.Namespace.hl })
  vim.api.nvim_set_hl(0, "TroubleIconNull", { link = vim.__icons.lsp_kinds.Null.hl })
  vim.api.nvim_set_hl(0, "TroubleIconNumber", { link = vim.__icons.lsp_kinds.Number.hl })
  vim.api.nvim_set_hl(0, "TroubleIconObject", { link = vim.__icons.lsp_kinds.Object.hl })
  vim.api.nvim_set_hl(0, "TroubleIconOperator", { link = vim.__icons.lsp_kinds.Operator.hl })
  vim.api.nvim_set_hl(0, "TroubleIconPackage", { link = vim.__icons.lsp_kinds.Package.hl })
  vim.api.nvim_set_hl(0, "TroubleIconProperty", { link = vim.__icons.lsp_kinds.Property.hl })
  vim.api.nvim_set_hl(0, "TroubleIconString", { link = vim.__icons.lsp_kinds.String.hl })
  vim.api.nvim_set_hl(0, "TroubleIconStruct", { link = vim.__icons.lsp_kinds.Struct.hl })
  vim.api.nvim_set_hl(0, "TroubleIconTypeParameter", { link = vim.__icons.lsp_kinds.TypeParameter.hl })
  vim.api.nvim_set_hl(0, "TroubleIconVariable", { link = vim.__icons.lsp_kinds.Variable.hl })
end

return M
