column_width = 9999
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "ForceSingle"
call_parentheses = "Input"
collapse_simple_statement = "Never"

[sort_requires]
enabled = true
