local icons = {
  unix = '',
  mac = '',
  windows = '',
  activelsp = '',
  activets = '',
  arrow_left_1 = '',
  arrow_right_1 = '',
  arrow_right_2 = '➜',
  bookmarks = '',
  bufferclose = '󰅖',
  dapbreakpoint = '',
  cursor = '󰆿',
  circular_big = '',
  circular_mid = '●',
  circular_mid_hollow = '●',
  dapbreakpointcondition = '',
  dapbreakpointrejected = '',
  daplogpoint = '.>',
  dapstopped = '󰁕',
  debugger = '',
  pen = '✎',
  file_1 = '󰈙',
  file_2 = '',
  directory = '',
  diagnostic = '󰒡',
  diagnostic_err = '',
  diagnostic_hint = '󰰁',
  diagnostic_info = '',
  diagnostic_warn = '', -- 󰰮
  ellipsis = '…',
  star = '★',
  filenew = '',
  filemodified = '',
  filereadonly = '',
  dir_closed = '',
  dir_opened = '',
  dir_empty_opend = '',
  dir_empty_closed = '',
  git = '󰊢',
  git_add = '',
  git_branch1 = '',
  git_branch2 = '',
  git_branch3 = '',
  git_branch4 = '',
  git_change = '',
  git_conflict = '',
  git_delete = '',
  git_ignored = '◌',
  git_renamed = '󰁕', -- ➜
  git_sign = '▎',
  git_staged = '',
  git_unstaged = '',
  git_untracked = '',
  lsp_loaded = '',
  lsp_loading1 = '',
  lsp_loading2 = '󰀚',
  lsp_loading3 = '',
  macrorecording = '',
  package = '󰏖',
  paste = '󰅌',
  refresh = '',
  search = '',
  selected = '❯',
  session = '󱂬',
  sort = '󰒺',
  spellcheck = '󰓆',
  tab = '󰓩',
  tabclose = '󰅙',
  terminal = '',
  wordfile = '󰈭',
  space = ' ',
  type = '󰊄',
  text = '󰉿',
  func = '󰊕',
  box_1 = '󰆧',
  box_2 = '',
  box_3 = '',
  setting = '',
  config = '',
  wrench = '',
  tag = '󰜢',
  alpha = '󰀫',
  shape = '',
  interface = '',
  namespace = '',
  ruler = '󰑭',
  array = '󰅪',
  numbers = '󰎠',
  enum = '󰕘',
  chars_1 = '',
  chars_2 = '󰀬',
  key = '󰌋',
  code = '',
  source = '',
  play = '',
  colors = '󰏘',
  entrance = '󰈇',
  pi = '󰏿',
  electricity_1 = '',
  electricity_2 = '',
  math = '󰆕',
  struct = '󰙅',
  rabbit = '󰤇',
  cat = '󰄛',
  left_half_1 = '',
  right_half_1 = '',
  left_harf_2 = '',
  right_harf_2 = '',
  progress = '',
  location = '',
  alarm = '󰀠',
  clock = '',
  closepand = '',
  expand = '',
  indent_marker_1 = '┆',
  indent_marker_2 = '└',
  indent_marker_3 = '│',
  symbol = '󰆧',
  files_1 = '󰉓',
  files_2 = '󱔗',
  static = '󰠄',
  backhole = '󰟢',
  window = '◩',
  cmd = '',
  import = '',
  keyboard = '',
  sleep = '󰒲',
  vim = '',
  lua = '󰢱',
  yes = '✔',
  spinner_frames = { '⣾', '⣽', '⣻', '⢿', '⡿', '⣟', '⣯', '⣷' },
}
icons.lsp_kinds = {
  Text = { val = icons.text, hl_link = 'GruvboxOrange' },
  Method = { val = icons.box_1, hl_link = 'GruvboxBlue' },
  Function = { val = icons.func, hl_link = 'GruvboxBlue' },
  Constructor = { val = icons.wrench, hl_link = 'GruvboxYellow' },
  Field = { val = icons.box_3, hl_link = 'GruvboxBlue' },
  Variable = { val = icons.alpha, hl_link = 'GruvboxOrange' },
  Class = { val = icons.shape, hl_link = 'GruvboxYellow' },
  Object = { val = icons.shape, hl_link = 'GruvboxYellow' },
  Interface = { val = icons.interface, hl_link = 'GruvboxYellow' },
  Module = { val = icons.namespace, hl_link = 'GruvboxBlue' },
  Namespace = { val = icons.namespace, hl_link = 'GruvboxBlue' },
  Property = { val = icons.box_3, hl_link = 'GruvboxBlue' },
  Unit = { val = icons.ruler, hl_link = 'GruvboxBlue' },
  Value = { val = icons.numbers, hl_link = 'GruvboxOrange' },
  Number = { val = icons.numbers, hl_link = 'GruvboxOrange' },
  Array = { val = icons.array, hl_link = 'GruvboxOrange' },
  Enum = { val = icons.enum, hl_link = 'GruvboxYellow' },
  Keyword = { val = icons.key, hl_link = 'GruvboxPurple' },
  Key = { val = icons.key, hl_link = 'GruvboxPurple' },
  Snippet = { val = icons.code, hl_link = 'GruvboxGreen' },
  Color = { val = icons.colors, hl_link = 'GruvboxPurple' },
  File = { val = icons.file_1, hl_link = 'GruvboxBlue' },
  Reference = { val = icons.entrance, hl_link = 'GruvboxPurple' },
  Folder = { val = icons.directory, hl_link = 'GruvboxBlue' },
  EnumMember = { val = icons.chars_1, hl_link = 'GruvboxAqua' },
  String = { val = icons.chars_2, hl_link = 'GruvboxGreen' },
  Constant = { val = icons.pi, hl_link = 'GruvboxOrange' },
  Struct = { val = icons.struct, hl_link = 'GruvboxYellow' },
  Event = { val = icons.electricity_1, hl_link = 'GruvboxPurple' },
  Operator = { val = icons.math, hl_link = 'GruvboxYellow' },
  TypeParameter = { val = icons.type, hl_link = 'GruvboxYellow' },
  Package = { val = icons.package, hl_link = 'GruvboxAqua' },
  StaticMethod = { val = icons.static, hl_link = 'GruvboxYellow' },
  Null = { val = icons.backhole, hl_link = 'GruvboxGray' },
  Boolean = { val = icons.window, hl_link = 'GruvboxPurple' },
}
icons.lsp_menus = {
  nvim_lsp   = '[LSP]',
  luasnip    = '[SNIP]',
  buffer     = '[BUFF]',
  async_path = '[PATH]',
}

icons.get_all_lsp_hllink = function ()
  local ret = {}

  for type, tb in pairs(icons.lsp_kinds) do
    if TOOLS.is_callable(tb) then
      goto continue
    end

    ret[type] = tb.hl_link

    ::continue::
  end

  return ret
end

return icons